ABBREVIATION_GLOSSARY = [
    {"abbr": "ssw", "meaning": "Gestational weeks"},
    {"abbr": "bdsys", "meaning": "Systolic Blood Pressure"},
    {"abbr": "bddia", "meaning": "Diastolic Blood Pressure"},
    {"abbr": "RR", "meaning": "Blood Pressure"},
    {"abbr": "_bd_", "meaning": "Blood Pressure"},
    {"abbr": "M1", "meaning": "Measurement 1"},
    {"abbr": "sys", "meaning": "Systolic"},
    {"abbr": "dia", "meaning": "Diastolic"},
    {"abbr": "SBP", "meaning": "Systolic Blood Pressure"},
    {"abbr": "DBP", "meaning": "Diastolic Blood Pressure"},
    {"abbr": "MAP", "meaning": "Mean Arterial Pressure"},
    {"abbr": "Tumor_Origin", "meaning": "Tumor Origin and Location"},
    {"abbr": "Specify_Other_Origin", "meaning": "Specify Other Tumor Origin"},
    {"abbr": "Location_Breast_Prostate", "meaning": "Tumor Location (Breast/Prostate)"},
    {"abbr": "Location_Colorectum", "meaning": "Tumor Location (Colon/Rectum)"},
    {"abbr": "Location_Lung", "meaning": "Tumor Location (Lung)"},
    {"abbr": "Other location_lung", "meaning": "Other Lung Location"},
    {"abbr": "Specify_Other_Location", "meaning": "Specify Other Tumor Location"},
    {"abbr": "Date_Surgery", "meaning": "Date of Surgery"},
    {"abbr": "Age at Surgery", "meaning": "Age at Surgery"},
    {"abbr": "Sex", "meaning": "Sex"},
    {"abbr": "Pathol_Acc_No", "meaning": "Pathology Accession Number"},
    {"abbr": "Other_Acc_No", "meaning": "Other Accession Number"},
    {"abbr": "BlockNum_Tumor", "meaning": "Tumor Block Number"},
    {"abbr": "BlockNum_Normal", "meaning": "Normal Tissue Block Number"},
    {"abbr": "BlockNum_Metastatic", "meaning": "Metastatic Block Number"},
    {"abbr": "BlockNum_Precancerous", "meaning": "Precancerous Block Number"},
    {"abbr": "InvitroSize1", "meaning": "In Vitro Size 1"},
    {"abbr": "InvitroSize2", "meaning": "In Vitro Size 2"},
    {"abbr": "InvitroSize3", "meaning": "In Vitro Size 3"},
    {"abbr": "PerineuralInvasion", "meaning": "Perineural Invasion"},
    {"abbr": "Vascular invasion present", "meaning": "Vascular Invasion Present"},
    {"abbr": "Surgical margin cancer present", "meaning": "Surgical Margin Cancer Present"},
    {"abbr": "Clin_Diagn_Breast", "meaning": "Clinical Diagnosis Breast Cancer"},
    {"abbr": "Lab_Diagn_Breast", "meaning": "Laboratory Diagnosis Breast Cancer"},
    {"abbr": "ILC_Subtype", "meaning": "ILC Subtype"},
    {"abbr": "Specify_If_Other_Type_Br", "meaning": "Specify If Other Breast Cancer Type"},
    {"abbr": "Clin_Grade_Breast", "meaning": "Clinical Grade Breast Cancer"},
    {"abbr": "Lab_Grade_Breast", "meaning": "Laboratory Grade Breast Cancer"},
    {"abbr": "Estrogen Receptor", "meaning": "Estrogen Receptor"},
    {"abbr": "Progesterone Receptor", "meaning": "Progesterone Receptor"},
    {"abbr": "HER2_Immunohistochemistry", "meaning": "HER2 Immunohistochemistry"},
    {"abbr": "HER2_FISH", "meaning": "HER2 FISH"},
    {"abbr": "BC_MolecularSubtype", "meaning": "Breast Cancer Molecular Subtype"},
    {"abbr": "Ki-67", "meaning": "Ki-67 Proliferation Index"},
    {"abbr": "p53_IHC", "meaning": "p53 Immunohistochemistry"},
    {"abbr": "DNA Index", "meaning": "DNA Index"},
    {"abbr": "BC_Precancerous", "meaning": "Breast Precancerous Lesion"},
    {"abbr": "TNMbreast_PrimTum(T)", "meaning": "TNM Breast Cancer - Primary Tumor (T)"},
    {"abbr": "TNMbreast_LN (N)", "meaning": "TNM Breast Cancer - Lymph Nodes (N)"},
    {"abbr": "TNMbreast_DistantMetast (M)", "meaning": "TNM Breast Cancer - Distant Metastases (M)"},
    {"abbr": "Clin_Diagn_Prostate", "meaning": "Clinical Diagnosis Prostate Cancer"},
    {"abbr": "Lab_Diag_Prostate", "meaning": "Laboratory Diagnosis Prostate Cancer"},
    {"abbr": "Specify_If_Other_type_Pro", "meaning": "Specify If Other Prostate Cancer Type"},
    {"abbr": "Clin_Gleason_Score", "meaning": "Clinical Gleason Score"},
    {"abbr": "Clin_Grade_Pro", "meaning": "Clinical Grade Prostate Cancer"},
    {"abbr": "Lab_Gleason_Score", "meaning": "Laboratory Gleason Score"},
    {"abbr": "Lab_Grade_Pro", "meaning": "Laboratory Grade Prostate Cancer"},
    {"abbr": "TNMprostate_T", "meaning": "TNM Prostate Cancer - T Stage"},
    {"abbr": "TNMprostate_N", "meaning": "TNM Prostate Cancer - N Stage"},
    {"abbr": "TNMprostate_M", "meaning": "TNM Prostate Cancer - M Stage"},
    {"abbr": "PSA_Level", "meaning": "PSA Level"},
    {"abbr": "SeminalInvasion", "meaning": "Seminal Vesicle Invasion"},
    {"abbr": "ExtraProstate Extention", "meaning": "Extraprostatic Extension"},
    {"abbr": "Clin_Diagn_Colon", "meaning": "Clinical Diagnosis Colon Cancer"},
    {"abbr": "If others_specify", "meaning": "If Others Specify"},
    {"abbr": "Lab_Diagn_Colon", "meaning": "Laboratory Diagnosis Colon Cancer"},
    {"abbr": "Clin_Grade_Colon", "meaning": "Clinical Grade Colon Cancer"},
    {"abbr": "Lab_Grade_Colon", "meaning": "Laboratory Grade Colon Cancer"},
    {"abbr": "TNMcolon_T", "meaning": "TNM Colon Cancer - T Stage"},
    {"abbr": "TNMcolon_N", "meaning": "TNM Colon Cancer - N Stage"},
    {"abbr": "TNMcolon_M", "meaning": "TNM Colon Cancer - M Stage"},
    {"abbr": "Pre-cancerous_Colon", "meaning": "Precancerous Lesion Colon"},
    {"abbr": "Clin_Diagn_Lung", "meaning": "Clinical Diagnosis Lung Cancer"},
    {"abbr": "Lab_Diagn_Lung", "meaning": "Laboratory Diagnosis Lung Cancer"},
    {"abbr": "If_Others_Specify", "meaning": "If Others Specify"},
    {"abbr": "Clin_Grade_Lung", "meaning": "Clinical Grade Lung Cancer"},
    {"abbr": "Lab_Grade_Lung", "meaning": "Laboratory Grade Lung Cancer"},
    {"abbr": "TNMlung_T", "meaning": "TNM Lung Cancer - T Stage"},
    {"abbr": "TNMlung_N", "meaning": "TNM Lung Cancer - N Stage"},
    {"abbr": "TNMlung_M", "meaning": "TNM Lung Cancer - M Stage"},
    {"abbr": "Clin_Diagn_Others", "meaning": "Clinical Diagnosis Other Cancers"},
    {"abbr": "Lab_Diagn_Others", "meaning": "Laboratory Diagnosis Other Cancers"},
    {"abbr": "Clin_Grade_Others", "meaning": "Clinical Grade Other Cancers"},
    {"abbr": "Lab_Grade_Others", "meaning": "Laboratory Grade Other Cancers"},
    {"abbr": "TNM_Stage", "meaning": "TNM Stage (Other Cancers)"},
    {"abbr": "PatholReview_Note", "meaning": "Pathology Review Note"}
]